version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@1.2.2 ## Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: ## Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sweater_weather_test
          POSTGRES_PASSWORD: ENV['SWEATER_WEATHER_DB_PASSWORD']
    working_directory: ~/sweater_weather
    executor: ruby/default
    steps:
      - checkout
      ## Bundle install dependencies
      - run: gem install bundler -v 2.1.4
      - run: bundle install
      # - ruby/bundle-install
      ## Database setup
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rspec
      - store_test_results:
          path: /tmp/test-reports
